[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI
    lvgl/lvgl

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE