[env:esp32c6]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino

lib_deps =
  bodmer/TFT_eSPI
  bblanchon/ArduinoJson

build_flags =
  -D USER_SETUP_LOADED=1
  -D DISABLE_ALL_LIBRARY_WARNINGS
  -D TFT_ESPI_DISABLE_GPIO_DIRECT